# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: flask-docker
#   namespace: "321498067920"
#   selfLink: /apis/serving.knative.dev/v1/namespaces/321498067920/services/flask-docker
#   uid: e07894fc-fc8a-4952-bcbc-8635466fbd43
#   resourceVersion: AAYH9uJovAY
#   generation: 14
#   creationTimestamp: "2023-10-17T19:03:25.114852Z"
#   labels:
#     cloud.googleapis.com/location: us-central1
#   annotations:
#     serving.knative.dev/creator: kiritiaryal1@gmail.com
#     serving.knative.dev/lastModifier: kiritiaryal1@gmail.com
#     run.googleapis.com/operation-id: 42183d25-8132-48fa-bce7-2af0fc1d5c1b
#     run.googleapis.com/ingress: all
#     run.googleapis.com/ingress-status: all
# spec:
#   template:
#     metadata:
#       labels:
#         client.knative.dev/nonce: uhpcxxofqg
#         run.googleapis.com/startupProbeType: Custom
#       annotations:
#         run.googleapis.com/client-name: gcloud
#         run.googleapis.com/client-version: 451.0.0
#         autoscaling.knative.dev/maxScale: "100"
#     spec:
#       containerConcurrency: 80
#       timeoutSeconds: 300
#       serviceAccountName: 321498067920-compute@developer.gserviceaccount.com
#       containers:
#         - image: "kiritiaryal/flask_docker:0.0.8"
#           ports:
#             - name: http1
#               containerPort: 3000
#           resources:
#             limits:
#               memory: 512Mi
#               cpu: 1000m
#           startupProbe:
#             timeoutSeconds: 1
#             periodSeconds: 10
#             failureThreshold: 3
#             tcpSocket:
#               port: 3000
#   traffic:
#     - percent: 100
#       latestRevision: true
