# conguration for gcloud run service
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flask-docker
  namespace: "321498067920"

  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: uhpcxxofqg
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 451.0.0
    spec:
      containers:
        - image: kiritiaryal/flask_docker:latest
          ports:
            - name: http1
              containerPort: 3000
          startupProbe:
            tcpSocket:
              port: 3000
  traffic:
    - percent: 100
      latestRevision: true
