apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flask-docker
  namespace: "321498067920"

  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: gcloud
    serving.knative.dev/creator: kiritiaryal1@gmail.com
    serving.knative.dev/lastModifier: kiritiaryal1@gmail.com
    run.googleapis.com/client-version: 451.0.0
    run.googleapis.com/operation-id: f260ba32-0fff-4d1c-ab12-4745fabcea62
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: uhpcxxofqg
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 451.0.0
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 321498067920-compute@developer.gserviceaccount.com
      containers:
        - image: kiritiaryal/flask_docker:0.0.5
          ports:
            - name: http1
              containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 3000
  traffic:
    - percent: 100
      latestRevision: true
